Range のサンプルコードにシンタックスハイライトを適用
rurema/doctree pull request #2410
Opened 2020-12-12 03:22 UTC by sanfrecce-osaka

refs #1546

## やったこと

- 旧記法(インデントで表現)を新記法(`#@samplecode` で表現)に修正
- 例: ... はサンプルコードのタイトルとして適用

2020-12-13 14:07 UTC, hanachin requested changes

2020-12-13 14:07 UTC, hanachin commented on refm/api/src/_builtin/Range
> +#@end
@sanfrecce-osaka ここだけ前の記法に戻してもらえないでしょうか :pray: (シンタックスエラーのコードのシンタックスハイライトはできないため)

```suggestion
  p(..)  # => SyntaxError
  p(...) # Ruby 2.7 で導入されたメソッド引数の forward として解釈されてしまう
```

2020-12-14 23:23 UTC, sanfrecce-osaka commented on refm/api/src/_builtin/Range
> +#@end
すみません、指摘ありがとうございます 🙇 
対応しました〜 🙏

2020-12-22 15:40 UTC, hanachin approved these changes

2020-12-22 15:40 UTC, merged