CSV::Tableの説明・サンプルコードの追加等
rurema/doctree pull request #2648
Opened 2022-01-09 18:41 UTC by universato

全体的にCSV::Tableの説明などを加えました。

例えば、`empty?`は、`Array#empty?`に委譲しているという説明のみで済ませられていましたが、
ヘッダーを除くことは必ずしも自明ではないため、説明やサンプルコードがあった方がいいと思います。

2022-04-06 06:15 UTC, znz requested changes

2022-04-06 06:15 UTC, znz commented on refm/api/src/csv/CSV__Table
> +puts table[0..2]
次の行の出力がでるのは `puts` ではなく `p` のようでした。
```suggestion
p table[0..2]
```

2022-04-06 06:15 UTC, znz commented on refm/api/src/csv/CSV__Table
> +table.inspect # => "#<CSV::Table mode:col_or_row row_count:2>"
出力例があるところに `p` をつけるなら、全部ついていた方が便利そうです。

```suggestion
p table.inspect # => "#<CSV::Table mode:col_or_row row_count:2>"
```

2022-04-06 06:15 UTC, znz commented on refm/api/src/csv/CSV__Table
> +table.empty?     # => true
```suggestion
p table.empty?     # => true
```

2022-04-06 06:15 UTC, znz commented on refm/api/src/csv/CSV__Table
> +table.empty?     # => false
```suggestion
p table.empty?     # => false
```

2022-04-06 06:15 UTC, znz commented on refm/api/src/csv/CSV__Table
> +table.to_csv(write_headers: false) # => "1,2,3\n"
```suggestion
p table.to_csv                       # => "a,b,c\n1,2,3\n"
p table.to_csv(write_headers: false) # => "1,2,3\n"
```

2022-10-05 07:03 UTC, universato commented
遅くなりましたが、コメント頂いたものについて、そのまま変更しました。よろしくお願いします！

2022-10-09 02:24 UTC, znz approved these changes

2022-10-09 02:24 UTC, merged

2022-10-09 02:24 UTC, znz commented
ありがとうございます。