rbconfig/sizeof を追加
rurema/doctree pull request #2835
Opened 2023-10-03 23:14 UTC by kyanagi

rbconfig/sizeof を追加します。

rbconfig/sizeof は 2.1.0 から、
RbConfig::LIMITS は 2.5.0 から利用可能です。

2023-10-12 03:00 UTC, znz requested changes
ruby head (3.3) での CI の失敗は master で修正できたはずなので、rebase もお願いします。

2023-10-12 03:00 UTC, znz commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['int'] # => 4
https://github.com/rurema/doctree/issues/433 の説明にあるように `require` を含めたコード例でお願いします。

2023-10-12 03:00 UTC, znz commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['INT_MAX'] # => 2147483647
こちらも同様です。

2023-10-13 07:11 UTC, kyanagi commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['int'] # => 4
require を追加しました。

2023-10-13 07:12 UTC, kyanagi commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['INT_MAX'] # => 2147483647
require を追加しました。

2023-10-14 02:57 UTC, znz commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['INT_MAX'] # => 2147483647
参照している定数が間違っているようでした。

```suggestion
RbConfig::LIMITS['INT_MAX'] # => 2147483647
```

2023-10-14 04:18 UTC, kyanagi commented on refm/api/src/rbconfig/sizeof.rd
> +RbConfig::SIZEOF['INT_MAX'] # => 2147483647
失礼しました。
修正をコミットしました。

2023-10-17 12:25 UTC, znz approved these changes
ありがとうございます。

2023-10-17 12:25 UTC, merged