Update to_date, to_datetime and to_time
rurema/doctree pull request #2872
Opened 2024-02-11 15:07 UTC by foomin10

Fix #2848 

Date および DateTime クラスの
#to_date、#to_datetime、#to_time メソッドを修正しました。

Date#to_date、DateTime#to_datetime は self を返します。

- RDoc
  - [Date](https://docs.ruby-lang.org/en/3.3/Date.html)
  - [DateTime](https://docs.ruby-lang.org/en/3.3/DateTime.html)

2024-05-10 07:45 UTC, znz requested changes

2024-06-11 09:26 UTC, foomin10 commented on refm/api/src/date/Date
>  --- to_date -> Date
修正しました。

2026-06-22 08:18 UTC, znz approved these changes

2026-06-22 08:19 UTC, znz commented
時間が経ってしまいましたが、conflictを修正してマージします。
ありがとうございます。

2026-06-22 08:19 UTC, merged

2026-06-27 11:15 UTC, foomin10 commented
おつかれさまです。