FrozenError since 2.5.0
rurema/doctree pull request #933
Opened 2017-12-26 12:12 UTC by znz

2017-12-31 12:24 UTC, sho-h requested changes
_builtin.rdにFrozenErrorのエントリが必要じゃないかと思ったくらいでしたー。

2018-01-03 06:25 UTC, znz commented
追加しました。

2018-01-03 08:38 UTC, sho-h approved these changes

2018-01-03 08:39 UTC, sho-h commented
特になくなりましたー。 👍

2018-01-10 14:50 UTC, merged