Add `keyword_init:` to `Struct.new` since 2.5.0
rurema/doctree pull request #937
Opened 2017-12-26 12:18 UTC by znz

2017-12-31 09:30 UTC, sho-h requested changes
各行にコメントさせてもらった点以外に以下が気になりましたけど、特に追加で記載できる事もなさそうですので、分岐だけ修正したいと思いましたー。

* Struct::Tmsはどうなのか -> keyword_initでは定義されていない
* keyword_init指定かどうかを知るわかりやすい方法はあるか(あればもう少し追記したかった) -> 既に載っているinspectの例以外では特殊な事が必要そう

2018-01-03 09:58 UTC, znz commented
`#@since 2.5.0 ... #@end` を追加しました。

`keyword_init: true` かどうかを知る方法は全くないのは不安だとお願いしてみたら、 Active Record で columns の情報が出るのと同じような感じで `inspect` には出るようにしてもらえたという感じで、 https://github.com/ruby/ruby/commit/8411f58ed70c1e6dc4e35589c94fd231c4e384d2 のコミットログに書いてあるように、調べるためのメソッドは今のところありません。(use case とともに要望を出せば追加される可能性はあります。)

2018-01-04 01:49 UTC, sho-h approved these changes

2018-01-04 01:51 UTC, sho-h commented
分岐の追加ありがとうございました！( `@param` の事だと書き漏らしてました...orz

keyword_init: trueの話も了解です！

2018-01-10 14:51 UTC, merged